name: 'Branch Merge'
description: 'Automatically merge branches.'
author: 'Daniele E. Domenichelli'
branding:
  icon: 'git-merge'
  color: 'orange'
inputs:
  source_branch:
    description: 'Name of the source branch'
    required: true
  target_branch:
    description: 'Name of the target branch'
    required: true
  allow_ff:
    description: 'Allow fast forward merge'
    required: false
    default: false
  allow_git_lfs:
    description: 'Allow git lfs support'
    required: false
    default: false
  ff_only:
    description: 'Refuse to perform a non fast forward merge (requires allow_ff=true)'
    required: false
    default: false
  allow_forks:
    description: 'Allow action to run on forks'
    required: false
    default: false
  user_name:
    description: 'User name for git commits'
    required: false
    default: 'GitHub Merge Action'
  user_email:
    description: 'User email for git commits'
    required: false
    default: 'actions@github.com'
  push_token:
    description: 'Environment variable containing the token to use for push'
    required: false
    default: 'GITHUB_TOKEN'
  commit_message_template:
    description: 'Merge commit message'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
